// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe9wbKHZLoLUIVBxeySWaYck1ocz2kOxU',
    appId: '1:26052677132:web:0d4ce7a7d910d8e4996829',
    messagingSenderId: '26052677132',
    projectId: 'notebookpro-7edc0',
    authDomain: 'notebookpro-7edc0.firebaseapp.com',
    storageBucket: 'notebookpro-7edc0.firebasestorage.app',
    measurementId: 'G-ZKWXDZE3JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADjMj1OuYwvewfbzFkhcDYeheWBwVW3_U',
    appId: '1:26052677132:android:df259dd28e4a3e81996829',
    messagingSenderId: '26052677132',
    projectId: 'notebookpro-7edc0',
    storageBucket: 'notebookpro-7edc0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe9wbKHZLoLUIVBxeySWaYck1ocz2kOxU',
    appId: '1:26052677132:web:bd8dba522763b1aa996829',
    messagingSenderId: '26052677132',
    projectId: 'notebookpro-7edc0',
    authDomain: 'notebookpro-7edc0.firebaseapp.com',
    storageBucket: 'notebookpro-7edc0.firebasestorage.app',
    measurementId: 'G-BMM0ER7LXP',
  );
}
